/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITagsRepo__factory } from "./ITagsRepo__factory";
export { TagsRepo__factory } from "./TagsRepo__factory";
