/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as recordSol from "./Record.sol";
export type { recordSol };
import type * as tagRepoSol from "./TagRepo.sol";
export type { tagRepoSol };
export type { Lock } from "./Lock";
